/**
 * @description A type that represents the properties that can be used in the system
 */
export type BackgroundColor = "backgroundColor"
export type BorderColor = "borderColor"
export type BorderStyle = "borderStyle"
export type BorderWidth = "borderWidth"
export type Color = "color"
export type AccentColor = "accentColor"
export type FontFamily = "fontFamily"
export type FontSize = "fontSize"
export type Gap = "gap"
export type Height = "height"
export type Inherit = "inherit"
export type LetterSpacing = "letterSpacing"
export type LineHeight = "lineHeight"
export type Margin = "margin"
export type Outline = "outline"
export type Padding = "padding"
export type ScaleFactor = "scaleFactor"
export type ShadowColor = "shadowColor"
export type Transparent = "transparent"
export type Type = "type"
export type Unit = "unit"
export type Weight = "weight"
export type Width = "width"
